# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'generation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10generation.proto\x12\x19intel_query_ai.generation\"_\n\x0eInsightMessage\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x12\n\nkey_topics\x18\x02 \x03(\t\x12\x14\n\x0ckey_insights\x18\x03 \x03(\t\x12\x12\n\nconclusion\x18\x04 \x01(\t\"\x8e\x01\n\x17GenerateInsightsRequest\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65tected_objects\x18\x02 \x03(\t\x12\x10\n\x08ocr_text\x18\x03 \x03(\t\x12\x17\n\x0fgraphs_detected\x18\x04 \x01(\x08\x12\x1a\n\x12graph_descriptions\x18\x05 \x03(\t\"W\n\x18GenerateInsightsResponse\x12;\n\x08insights\x18\x01 \x01(\x0b\x32).intel_query_ai.generation.InsightMessage\"?\n\x16GenerateSummaryRequest\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x11\n\tmax_chars\x18\x02 \x01(\x05\"*\n\x17GenerateSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\"|\n\x12\x41nswerQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65tected_objects\x18\x03 \x03(\t\x12\x10\n\x08ocr_text\x18\x04 \x03(\t\x12\x17\n\x0fgraphs_detected\x18\x05 \x01(\x08\"%\n\x13\x41nswerQueryResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd1\x03\n\x11GenerationService\x12{\n\x10GenerateInsights\x12\x32.intel_query_ai.generation.GenerateInsightsRequest\x1a\x33.intel_query_ai.generation.GenerateInsightsResponse\x12x\n\x0fGenerateSummary\x12\x31.intel_query_ai.generation.GenerateSummaryRequest\x1a\x32.intel_query_ai.generation.GenerateSummaryResponse\x12l\n\x0b\x41nswerQuery\x12-.intel_query_ai.generation.AnswerQueryRequest\x1a..intel_query_ai.generation.AnswerQueryResponse\x12W\n\x04Ping\x12&.intel_query_ai.generation.PingRequest\x1a\'.intel_query_ai.generation.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSIGHTMESSAGE']._serialized_start=47
  _globals['_INSIGHTMESSAGE']._serialized_end=142
  _globals['_GENERATEINSIGHTSREQUEST']._serialized_start=145
  _globals['_GENERATEINSIGHTSREQUEST']._serialized_end=287
  _globals['_GENERATEINSIGHTSRESPONSE']._serialized_start=289
  _globals['_GENERATEINSIGHTSRESPONSE']._serialized_end=376
  _globals['_GENERATESUMMARYREQUEST']._serialized_start=378
  _globals['_GENERATESUMMARYREQUEST']._serialized_end=441
  _globals['_GENERATESUMMARYRESPONSE']._serialized_start=443
  _globals['_GENERATESUMMARYRESPONSE']._serialized_end=485
  _globals['_ANSWERQUERYREQUEST']._serialized_start=487
  _globals['_ANSWERQUERYREQUEST']._serialized_end=611
  _globals['_ANSWERQUERYRESPONSE']._serialized_start=613
  _globals['_ANSWERQUERYRESPONSE']._serialized_end=650
  _globals['_PINGREQUEST']._serialized_start=652
  _globals['_PINGREQUEST']._serialized_end=682
  _globals['_PINGRESPONSE']._serialized_start=684
  _globals['_PINGRESPONSE']._serialized_end=715
  _globals['_GENERATIONSERVICE']._serialized_start=718
  _globals['_GENERATIONSERVICE']._serialized_end=1183
# @@protoc_insertion_point(module_scope)
