# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generation_pb2 as generation__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in generation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateInsights = channel.unary_unary(
                '/intel_query_ai.generation.GenerationService/GenerateInsights',
                request_serializer=generation__pb2.GenerateInsightsRequest.SerializeToString,
                response_deserializer=generation__pb2.GenerateInsightsResponse.FromString,
                _registered_method=True)
        self.GenerateSummary = channel.unary_unary(
                '/intel_query_ai.generation.GenerationService/GenerateSummary',
                request_serializer=generation__pb2.GenerateSummaryRequest.SerializeToString,
                response_deserializer=generation__pb2.GenerateSummaryResponse.FromString,
                _registered_method=True)
        self.AnswerQuery = channel.unary_unary(
                '/intel_query_ai.generation.GenerationService/AnswerQuery',
                request_serializer=generation__pb2.AnswerQueryRequest.SerializeToString,
                response_deserializer=generation__pb2.AnswerQueryResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/intel_query_ai.generation.GenerationService/Ping',
                request_serializer=generation__pb2.PingRequest.SerializeToString,
                response_deserializer=generation__pb2.PingResponse.FromString,
                _registered_method=True)


class GenerationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateInsights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnswerQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateInsights,
                    request_deserializer=generation__pb2.GenerateInsightsRequest.FromString,
                    response_serializer=generation__pb2.GenerateInsightsResponse.SerializeToString,
            ),
            'GenerateSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSummary,
                    request_deserializer=generation__pb2.GenerateSummaryRequest.FromString,
                    response_serializer=generation__pb2.GenerateSummaryResponse.SerializeToString,
            ),
            'AnswerQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.AnswerQuery,
                    request_deserializer=generation__pb2.AnswerQueryRequest.FromString,
                    response_serializer=generation__pb2.AnswerQueryResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=generation__pb2.PingRequest.FromString,
                    response_serializer=generation__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intel_query_ai.generation.GenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intel_query_ai.generation.GenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.generation.GenerationService/GenerateInsights',
            generation__pb2.GenerateInsightsRequest.SerializeToString,
            generation__pb2.GenerateInsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.generation.GenerationService/GenerateSummary',
            generation__pb2.GenerateSummaryRequest.SerializeToString,
            generation__pb2.GenerateSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnswerQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.generation.GenerationService/AnswerQuery',
            generation__pb2.AnswerQueryRequest.SerializeToString,
            generation__pb2.AnswerQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.generation.GenerationService/Ping',
            generation__pb2.PingRequest.SerializeToString,
            generation__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
