# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcription.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'transcription.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13transcription.proto\x12\x1cintel_query_ai.transcription\">\n\x11TranscribeRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12\x15\n\rlanguage_hint\x18\x02 \x01(\t\"=\n\x11TranscriptSegment\x12\r\n\x05start\x18\x01 \x01(\x01\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x01\x12\x0c\n\x04text\x18\x03 \x01(\t\"\xa6\x01\n\x12TranscribeResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t\x12\x12\n\ntimestamps\x18\x02 \x03(\x01\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x02\x12\x41\n\x08segments\x18\x05 \x03(\x0b\x32/.intel_query_ai.transcription.TranscriptSegment\"=\n\x10SummarizeRequest\x12\x12\n\ntranscript\x18\x01 \x01(\t\x12\x15\n\rmax_sentences\x18\x02 \x01(\x05\";\n\x11SummarizeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x15\n\rkey_sentences\x18\x02 \x03(\t\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd4\x02\n\x14TranscriptionService\x12o\n\nTranscribe\x12/.intel_query_ai.transcription.TranscribeRequest\x1a\x30.intel_query_ai.transcription.TranscribeResponse\x12l\n\tSummarize\x12..intel_query_ai.transcription.SummarizeRequest\x1a/.intel_query_ai.transcription.SummarizeResponse\x12]\n\x04Ping\x12).intel_query_ai.transcription.PingRequest\x1a*.intel_query_ai.transcription.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSCRIBEREQUEST']._serialized_start=53
  _globals['_TRANSCRIBEREQUEST']._serialized_end=115
  _globals['_TRANSCRIPTSEGMENT']._serialized_start=117
  _globals['_TRANSCRIPTSEGMENT']._serialized_end=178
  _globals['_TRANSCRIBERESPONSE']._serialized_start=181
  _globals['_TRANSCRIBERESPONSE']._serialized_end=347
  _globals['_SUMMARIZEREQUEST']._serialized_start=349
  _globals['_SUMMARIZEREQUEST']._serialized_end=410
  _globals['_SUMMARIZERESPONSE']._serialized_start=412
  _globals['_SUMMARIZERESPONSE']._serialized_end=471
  _globals['_PINGREQUEST']._serialized_start=473
  _globals['_PINGREQUEST']._serialized_end=503
  _globals['_PINGRESPONSE']._serialized_start=505
  _globals['_PINGRESPONSE']._serialized_end=536
  _globals['_TRANSCRIPTIONSERVICE']._serialized_start=539
  _globals['_TRANSCRIPTIONSERVICE']._serialized_end=879
# @@protoc_insertion_point(module_scope)
