# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeFrames = channel.unary_unary(
                '/intel_query_ai.vision.VisionService/AnalyzeFrames',
                request_serializer=vision__pb2.AnalyzeFramesRequest.SerializeToString,
                response_deserializer=vision__pb2.AnalyzeFramesResponse.FromString,
                _registered_method=True)
        self.DetectObjects = channel.unary_unary(
                '/intel_query_ai.vision.VisionService/DetectObjects',
                request_serializer=vision__pb2.DetectObjectsRequest.SerializeToString,
                response_deserializer=vision__pb2.DetectObjectsResponse.FromString,
                _registered_method=True)
        self.DetectGraphs = channel.unary_unary(
                '/intel_query_ai.vision.VisionService/DetectGraphs',
                request_serializer=vision__pb2.DetectGraphsRequest.SerializeToString,
                response_deserializer=vision__pb2.DetectGraphsResponse.FromString,
                _registered_method=True)
        self.ExtractText = channel.unary_unary(
                '/intel_query_ai.vision.VisionService/ExtractText',
                request_serializer=vision__pb2.ExtractTextRequest.SerializeToString,
                response_deserializer=vision__pb2.ExtractTextResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/intel_query_ai.vision.VisionService/Ping',
                request_serializer=vision__pb2.PingRequest.SerializeToString,
                response_deserializer=vision__pb2.PingResponse.FromString,
                _registered_method=True)


class VisionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectGraphs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeFrames': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFrames,
                    request_deserializer=vision__pb2.AnalyzeFramesRequest.FromString,
                    response_serializer=vision__pb2.AnalyzeFramesResponse.SerializeToString,
            ),
            'DetectObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObjects,
                    request_deserializer=vision__pb2.DetectObjectsRequest.FromString,
                    response_serializer=vision__pb2.DetectObjectsResponse.SerializeToString,
            ),
            'DetectGraphs': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectGraphs,
                    request_deserializer=vision__pb2.DetectGraphsRequest.FromString,
                    response_serializer=vision__pb2.DetectGraphsResponse.SerializeToString,
            ),
            'ExtractText': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractText,
                    request_deserializer=vision__pb2.ExtractTextRequest.FromString,
                    response_serializer=vision__pb2.ExtractTextResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=vision__pb2.PingRequest.FromString,
                    response_serializer=vision__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intel_query_ai.vision.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intel_query_ai.vision.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.vision.VisionService/AnalyzeFrames',
            vision__pb2.AnalyzeFramesRequest.SerializeToString,
            vision__pb2.AnalyzeFramesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.vision.VisionService/DetectObjects',
            vision__pb2.DetectObjectsRequest.SerializeToString,
            vision__pb2.DetectObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectGraphs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.vision.VisionService/DetectGraphs',
            vision__pb2.DetectGraphsRequest.SerializeToString,
            vision__pb2.DetectGraphsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.vision.VisionService/ExtractText',
            vision__pb2.ExtractTextRequest.SerializeToString,
            vision__pb2.ExtractTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intel_query_ai.vision.VisionService/Ping',
            vision__pb2.PingRequest.SerializeToString,
            vision__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
